package com.velocimetro.scooterlab

/**
 * Keeps the application-channel startup separate from a user-requested MiOT command.
 *
 * Xiaomi Home acknowledges the scooter's initial single-control message before opening a new
 * outbound flow. Without that receipt, the scooter can retain the channel in its startup state
 * and silently ignore a later command flow.
 */
class ScooterApplicationChannel {
    var state: ScooterApplicationChannelState = ScooterApplicationChannelState.INITIALIZING
        private set

    private var inboundFrameCount = 0
    private val receivedSequences = linkedSetOf<Int>()
    private val inboundPayloads = sortedMapOf<Int, ByteArray>()

    /**
     * Handles only channel-level receipts generated by the scooter. It never creates a physical
     * scooter command; the returned acknowledgement is a transport receipt for an inbound frame.
     */
    fun onInboundFrame(frame: ByteArray): ScooterApplicationChannelResult {
        val packet = ScooterChannelFraming.decode(frame)
        val wasReady = state == ScooterApplicationChannelState.READY
        var completedDataPayload: ByteArray? = null
        val responses = when (packet) {
            is ScooterChannelPacket.SingleControl -> listOf(ScooterChannelFraming.singleControlAcknowledgement())
            is ScooterChannelPacket.FlowControl -> {
                inboundFrameCount = packet.frameCount
                receivedSequences.clear()
                inboundPayloads.clear()
                listOf(ScooterChannelFraming.ack(status = flowAccepted))
            }
            is ScooterChannelPacket.DataFragment -> {
                if (inboundFrameCount > 0 && packet.sequence in 1..inboundFrameCount) {
                    receivedSequences += packet.sequence
                    inboundPayloads[packet.sequence] = packet.payload.copyOf()
                    if (receivedSequences.size == inboundFrameCount) {
                        completedDataPayload = inboundPayloads.values.fold(ByteArray(0)) { all, part -> all + part }
                        inboundFrameCount = 0
                        receivedSequences.clear()
                        inboundPayloads.clear()
                        listOf(ScooterChannelFraming.ack(status = dataAccepted))
                    } else {
                        emptyList()
                    }
                } else {
                    emptyList()
                }
            }
            else -> emptyList()
        }
        if (packet is ScooterChannelPacket.SingleControl || packet is ScooterChannelPacket.FlowControl) {
            state = ScooterApplicationChannelState.READY
        }
        return ScooterApplicationChannelResult(
            packet = packet,
            responseFrames = responses,
            becameReady = !wasReady && state == ScooterApplicationChannelState.READY,
            completedDataPayload = completedDataPayload,
        )
    }

    fun clear() {
        state = ScooterApplicationChannelState.INITIALIZING
        inboundFrameCount = 0
        receivedSequences.clear()
        inboundPayloads.clear()
    }

    /** Marks successful completion of the locally initiated, non-physical startup exchange. */
    fun markReady() {
        state = ScooterApplicationChannelState.READY
    }

    private companion object {
        const val flowAccepted = 1
        const val dataAccepted = 0
    }
}

enum class ScooterApplicationChannelState {
    INITIALIZING,
    READY,
}

data class ScooterApplicationChannelResult(
    val packet: ScooterChannelPacket,
    val responseFrames: List<ByteArray>,
    val becameReady: Boolean,
    val completedDataPayload: ByteArray? = null,
)
